name: std_dl
dependencies:
    - python=3.8
    - pip
    - pip:
      - cycler==0.11.0
      - fonttools==4.30.0
      - imageio==2.16.1
      - kiwisolver==1.3.2
      - matplotlib==3.5.1
      - networkx==2.7.1
      - numpy==1.22.3
      - packaging==21.3
      - pandas==1.4.1
      - pillow==9.0.1
      - pyparsing==3.0.7
      - python-dateutil==2.8.2
      - pytz==2021.3
      - pywavelets==1.2.0
      - scikit-image==0.19.2
      - scipy==1.8.0
      - seaborn==0.11.2
      - six==1.16.0
      - sklearn==1.0.2
      - tifffile==2022.2.9
      - torch==1.8.1+cu101
      - torchaudio==0.8.1
      - torchvision==0.9.1+cu101
      - typing_extensions==4.1.1
      - hydra-joblib-launcher
