deploy: False # Store run in wandb in True
tag: scratch  # Tag is used to determine logging-directory
seed: 0
device: cuda:0

reps: 10

loss:
  alpha: 0.5                 # Weighted loss function
  tune_alpha: False
  group_task_loss: True  # Avg losses based on task grouping

task:
  dataset: split_cifar10
  task_map: [[0,1], [2,3], [4,5], [6,7], [8,9]]
  target: 0
  ood: [4]
  augment: True
  n: 50        # Samples per label (NOTE: different from ashwin's code)
  m_n: 0      # Samples of OOD per label
  beta: 0.5      # either float or string "unbiased" to use n/n+m
  custom_sampler: True

  num_cinic: 200
  

hp: 
  epochs: 100
  bs: 16
  lr: 0.01

net: conv


# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
